- .travis.yml
Introduce trigger for unit tests
> chore(QA): Add Travis config to trigger unit tests

- qabot/manifests_checker.py
- qabot/qabot.py
- tests/test_manifests_checker.py
This should help us hunt down specific versions across all environments.
> chore(qa-bot): Allow bot to search for a version from any service

- qabot/qabot.py
> silly typo

- qabot/qabot.py
> small fix to process json blocks with whitespaces

- .travis.yml
- qabot/jenkins_job_invoker.py
- qabot/lib/jenkinslib.py
- tests/test_jenkinslib.py
Adopting multiple jenkins user api tokens.
> chore(qa): Tweak qa-bot to use multiple jenkins user api tokens

- qabot/lib/jenkinslib.py
check if http is found on the parameter value
> Another ultimate fix

- qabot/jenkins_job_invoker.py
- qabot/lib/jenkinslib.py
- qabot/qabot.py
- Introduce command to list environments.
> chore(qa-bot): Introduce command to list environments

- pyproject.toml
- qabot/jenkins_job_invoker.py
- qabot/lib/githublib.py
- qabot/lib/httplib.py
- qabot/lib/jenkinslib.py
- qabot/manifests_checker.py
- qabot/qabot.py
How to use:
```
@qa-bot replay-pr gen3-qa 549 test-portal-homepageTest,test-apis-dataUploadTest
```
> Chore(automation): Replay pr command

- qabot/qabot.py
Jira Ticket: [PXP-7312](https://ctds-planx.atlassian.net/browse/PXP-7312)
Adding `self-service-release` to the commands maps in qabot.py
> chore: adding service-release command

- qabot/jenkins_job_invoker.py
- qabot/lib/jenkinslib.py
Return the url of the replayed job to Slack.
> return the url of the replayed PR for people to click on

- qabot/jenkins_job_invoker.py
- qabot/lib/jenkinslib.py
- qabot/qabot.py
Let us introduce more ChatOps into our Selenium maintenance activities.
> chore(qa-bot): New cmd to check selenium status

- qabot/state_of_the_nation.py
Adding ACCOUNT project and environments to the `state-of-the-nation` report.
> chore(state-of-the-nation): Add acct to project mapping

- qabot/manifests_checker.py
Improving logic to properly track monthly releases.
> chore(whereis-release): Look at the sheepdog version and, if it does not exist, look at indexd

- qabot/lib/jenkinslib.py
- qabot/qabot.py
> chore(debug): Additional debugging for self-service-release

- qabot/qabot.py
Allow communication between bots (so bots can call other bots).
> chore(automation): Allow communication betweeen bots

- qabot/qabot.py
> fix(qabot): KeyError: 'username'

- .travis.yml
- README.md
- poetry.lock
- pyproject.toml
- qabot/lib/influxlib.py
- qabot/pipeline_maintenance.py
- qabot/qabot.py
- tests/test_pipeline_maintenance.py
This is a stepping stone for our auto-replay feature.
- New command: get-failure-rate
> task(failure-rate): Check failure rate of a given test suite

- qabot/pipeline_maintenance.py
- qabot/qabot.py
How to use it:
```
marcelo  3:20 PM
@qa-bot quarantine-ci-environment jenkins-new
qa-botAPP  3:20 PM
The environment jenkins-new has been placed under quarantine. :face_with_thermometer:
```
> chore(new-cmd): adding quarantine-ci-environment command

- qabot/lib/jenkinslib.py
Jira Ticket: [QAT-162](https://ctds-planx.atlassian.net/browse/QAT-162)
> QAT-162: JSON parsing issue when call qa-bot self-service-release
- Fix annoying error `ERROR:__main__:Expecting value: line 1 column 1 (char 0)`
> fix(qa-bot): Fix intermittent failure with json parsing

- qabot/pipeline_maintenance.py
- qabot/qabot.py
Add Quarantined env back into pool script
> chore(qa-bot): Introduce new command to unquarantine environment

- qabot/lib/jenkinslib.py
> fix(json-errors): import JSONDecodeError

- qabot/lib/jenkinslib.py
- qabot/pipeline_maintenance.py
- qabot/qabot.py
> chore(ci-tests): Check CI failures on Slack

- qabot/pipeline_maintenance.py
- qabot/qabot.py
Testing:
```
@qa-bot who-do-I-ask-about arborist
```
result:
```
primary: @avantol & secondary:@pauline
```
> chore(find-smes): introduce who-do-I-ask-about command

- Dockerfile
- README.md
- poetry.lock
- pyproject.toml
> chore(update-lib): Upgrade cryptography

- qabot/pipeline_maintenance.py
- qabot/qabot.py
> chore(nightly-build-stats): Post additional nightly build stats when jenkins sends a notification to #nightly-builds

- poetry.lock
- pyproject.toml
- qabot/pipeline_maintenance.py
- qabot/qabot.py
- tests/test_pipeline_maintenance.py
> chore(ci-summary): Print daily CI summary

- qabot/parse_codeowners.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> update self-service for gitops-qa codeowners

- qabot/parse_codeowners.py
> fix gitops-qa codeowners file url

- qabot/parse_codeowners.py
- qabot/release.py
Jira Ticket: [GQE-69](https://ctds-planx.atlassian.net/browse/GQE-69)
[GQE-69]: https://ctds-planx.atlassian.net/browse/GQE-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update qa envs in self-service-release

- qabot/pipeline_maintenance.py
Jira Ticket: [GQE-103](https://ctds-planx.atlassian.net/browse/GQE-103)
[GQE-103]: https://ctds-planx.atlassian.net/browse/GQE-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix env list in pool for quarantine to work right

- qabot/pipeline_maintenance.py
Jira Ticket: [GQE-38](https://ctds-planx.atlassian.net/browse/GQE-38)
[GQE-38]: https://ctds-planx.atlassian.net/browse/GQE-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add new envs to CI pool

- qabot/pipeline_maintenance.py
- qabot/release.py
Link to JIRA ticket if there is one: [GQE-539](https://ctds-planx.atlassian.net/browse/GQE-539)
[GQE-539]: https://ctds-planx.atlassian.net/browse/GQE-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Handle invalid github handle in self_service_release

- helm/qabot/templates/deployment.yaml
Link to JIRA ticket if there is one:
> Remove readinessProbe and livenessProbe

- qabot.py
- qabot/pipeline_maintenance.py
Link to JIRA ticket if there is one: [GQE-552](https://ctds-planx.atlassian.net/browse/GQE-552)
[GQE-552]: https://ctds-planx.atlassian.net/browse/GQE-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add nightly-build run replay support
